CREATE DATABASE loginsystem;
USE loginsystem;
CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE USER 'lsuser'@'%' IDENTIFIED BY '12345678';
GRANT ALL PRIVILEGES ON loginsystem.* TO 'lsuser'@'%';

FLUSH PRIVILEGES;
QUIT